export const userdata = [
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
  {
    name: "Rapheal Chizitere",
    username: "kingrashy",
    desc: "Hi, i'm kin what u?",
    status: "online",
  },
];
